# travis config dulu

language: android
jdk: oraclejdk11
cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - ANDROID_API_LEVEL=31
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
    - secure: hash value
android:
  licenses:
    - 'android-adk-preview-license-.+'
    - 'android-adk-license-.+'
    - 'google-adk-license-.+'
  components:
    - tools
    - platfrom-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-$ANDROID_API_LEVEL
before_script:
  - yes | sdkmanager "platforms;android-29"
script:
  - npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output /android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
  - chmod +x ./gradlew
  - cd android && ./gradlew assembleDebug

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-debug.apk
  skip_cleanup: true
  name: dev-build-$TRAVIS_TAG
  body: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    tags: true

after_deploy:
   - rm -rf $TRAVIS_BUILD_DIR/android/app/build/outputs